<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Tagihan;

class TagihanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Tagihan::insert([
            [
                'NRP' => 5026201000,
                'periodeTagihan' => '2020 - Ganjil',
                'status' => true,
                'bank' => 'BCA',
                'tanggal' => '2020-05-05',
                'SPP' => 3500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201000,
                'periodeTagihan' => '2020 - Genap',
                'status' => true,
                'bank' => 'BCA',
                'tanggal' => '2020-05-05',
                'SPP' => 3500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201000,
                'periodeTagihan' => '2021 - Ganjil',
                'status' => true,
                'bank' => 'BCA',
                'tanggal' => '2020-05-05',
                'SPP' => 3500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201139,
                'periodeTagihan' => '2020 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-05-05',
                'SPP' => 3500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201130,
                'periodeTagihan' => '2020 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-05-05',
                'SPP' => 2500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201141,
                'periodeTagihan' => '2020 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-05-05',
                'SPP' => 4500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201054,
                'periodeTagihan' => '2020 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-05-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201045,
                'periodeTagihan' => '2020 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-05-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201115,
                'periodeTagihan' => '2020 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-05-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201096,
                'periodeTagihan' => '2020 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-05-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201139,
                'periodeTagihan' => '2020 - Genap',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-11-05',
                'SPP' => 3500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201130,
                'periodeTagihan' => '2020 - Genap',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-11-05',
                'SPP' => 2500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201141,
                'periodeTagihan' => '2020 - Genap',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-11-05',
                'SPP' => 4500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201054,
                'periodeTagihan' => '2020 - Genap',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-11-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201045,
                'periodeTagihan' => '2020 - Genap',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-11-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201115,
                'periodeTagihan' => '2020 - Genap',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-11-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201096,
                'periodeTagihan' => '2020 - Genap',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2020-11-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201139,
                'periodeTagihan' => '2021 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2021-05-05',
                'SPP' => 3500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201130,
                'periodeTagihan' => '2021 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2021-05-05',
                'SPP' => 2500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201141,
                'periodeTagihan' => '2021 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2021-05-05',
                'SPP' => 4500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201054,
                'periodeTagihan' => '2021 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2021-05-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201045,
                'periodeTagihan' => '2021 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2021-05-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201115,
                'periodeTagihan' => '2021 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2021-05-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201096,
                'periodeTagihan' => '2021 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2021-05-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201109,
                'periodeTagihan' => '2021 - Ganjil',
                'status' => true,
                'bank' => 'BRI',
                'tanggal' => '2021-05-05',
                'SPP' => 5500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
            [
                'NRP' => 5026201130,
                'periodeTagihan' => '2022 - Ganjil',
                'status' => false,
                'bank' => 'BRI',
                'tanggal' => '0001-01-01',
                'SPP' => 2500000,
                'pelayaran' => 0,
                'tunggakPelayaran' => 0,
                'SPI' => 0,
                'IPITS' => 0,
                'penyegaran' => 0,
                'tunggakSPP' => 0,
                'tunggakSPI' => 0,
                'tunggakIPITS' => 0,
                'tunggakPenyegaran' => 0
            ],
        ]);
    }
}
